name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip custom_components
        run: |
          cd custom_components
          zip -r ../rainviewer.zip rainviewer/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: rainviewer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
